on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  dynamic-img-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine which image to use
        id: determine-image
        run: |
          hour=$(date +%H)
          if [ $((hour % 24)) -lt 6 ]; then
            echo "image=1.png" >> $GITHUB_ENV
          elif [ $((hour % 24)) -lt 12 ]; then
            echo "image=2.png" >> $GITHUB_ENV
          elif [ $((hour % 24)) -lt 18 ]; then
            echo "image=3.png" >> $GITHUB_ENV
          else
            echo "image=4.png" >> $GITHUB_ENV
          fi

      - name: Copy image to root and rename
        run: cp -f images/${{ env.image }} main.png

      - name: Commit and push changes
        run: |
          git config --global user.name 'Hérick Bittencourt'
          git config --global user.email 'acanixz@users.noreply.github.com'
          git add main.png
          git commit -m "Update main.png with ${{ env.image }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}